import { createFileRoute } from "@tanstack/react-router";
import { LegalPage } from "@/components/tangpt/LegalPage";

export const Route = createFileRoute("/privacy")({
  head: () => ({ meta: [
    { title: "Quyền riêng tư — TánGPT" },
    { name: "description", content: "Chính sách quyền riêng tư của TánGPT bằng tiếng Việt và tiếng Anh." },
    { property: "og:title", content: "Quyền riêng tư — TánGPT" },
    { property: "og:description", content: "Chính sách quyền riêng tư của TánGPT bằng tiếng Việt và tiếng Anh." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: () => <LegalPage titleVi="Chính sách bảo mật" titleEn="Privacy Policy" sections={[
    { vi: { title: "1. Phạm vi chính sách", body: ["Chính sách bảo mật này giải thích các loại dữ liệu cá nhân TánGPT thu thập, mục đích sử dụng dữ liệu và các lựa chọn của bạn khi sử dụng dịch vụ."] }, en: { title: "1. Scope of this Policy", body: ["This Privacy Policy explains the types of personal data TánGPT collects, why that data is used, and the choices available to you when you use the service."] } },
    { vi: { title: "2. Dữ liệu chúng tôi thu thập", body: ["Chúng tôi có thể thu thập số điện thoại dùng để xác thực tài khoản; thông tin tùy chọn về giới tính và cách xưng hô; lịch sử trò chuyện, ký ức và các lựa chọn cá nhân hóa trong ứng dụng; cùng thông tin cần thiết để ghi nhận giao dịch thanh toán.", "Thanh toán được xử lý bởi bên thứ ba. Chúng tôi không trực tiếp lưu trữ số thẻ thanh toán hoặc số tài khoản ngân hàng của bạn."] }, en: { title: "2. Data we collect", body: ["We may collect the phone number used to authenticate your account; optional gender and address-preference information; chat history, memories, and personalization choices within the app; and information needed to record payment transactions.", "Payments are processed by a third party. We do not directly store your payment card number or bank account number."] } },
    { vi: { title: "3. Mục đích sử dụng dữ liệu", body: ["Chúng tôi sử dụng dữ liệu để xác thực và quản lý tài khoản, cá nhân hóa trải nghiệm trò chuyện, ghi nhận và xử lý thanh toán, vận hành dịch vụ, khắc phục lỗi và cải thiện TánGPT."] }, en: { title: "3. How we use data", body: ["We use data to authenticate and manage accounts, personalize the chat experience, record and process payments, operate the service, resolve technical issues, and improve TánGPT."] } },
    { vi: { title: "4. Chia sẻ và bán dữ liệu", body: ["Chúng tôi không bán dữ liệu cá nhân của bạn cho bên thứ ba.", "Một số nhà cung cấp dịch vụ có thể xử lý dữ liệu thay mặt chúng tôi khi cần để cung cấp chức năng như xác thực, hạ tầng, xử lý thanh toán hoặc vận hành dịch vụ. Phạm vi và điều khoản xử lý cụ thể cần được luật sư xem xét trong bản chính thức."] }, en: { title: "4. Sharing and sale of data", body: ["We do not sell your personal data to third parties.", "Certain service providers may process data on our behalf where needed to provide functions such as authentication, infrastructure, payment processing, or service operation. The specific scope and contractual terms for that processing require legal review in the final version."] } },
    { vi: { title: "5. Lưu giữ và bảo vệ dữ liệu", body: ["Dữ liệu được lưu giữ trong thời gian cần thiết để cung cấp dịch vụ và thực hiện các mục đích nêu trong chính sách này, trừ khi pháp luật yêu cầu thời gian khác. Thời hạn lưu giữ chi tiết và các biện pháp bảo vệ cụ thể cần được luật sư xem xét trước khi chính sách được ban hành chính thức."] }, en: { title: "5. Data retention and protection", body: ["Data is retained for as long as needed to provide the service and fulfill the purposes described in this Policy, unless a different period is required by law. Detailed retention periods and specific safeguards require legal review before this Policy is issued as a final document."] } },
    { vi: { title: "6. Quyền xóa dữ liệu", body: ["Bạn có thể yêu cầu xóa toàn bộ dữ liệu cá nhân bất cứ lúc nào bằng tính năng “Xóa tài khoản và dữ liệu” trong mục “Tôi” của ứng dụng. Thao tác này xóa vĩnh viễn hồ sơ, nhân vật đồng hành, lịch sử trò chuyện và ký ức gắn với tài khoản của bạn.", "Một số thông tin có thể phải được giữ lại nếu pháp luật yêu cầu. Phạm vi ngoại lệ cụ thể cần được luật sư xem xét."] }, en: { title: "6. Your deletion rights", body: ["You may request deletion of all personal data at any time through the “Delete account and data” feature in the app's “Me” section. This permanently deletes your profile, companions, chat history, and memories associated with your account.", "Certain information may need to be retained where required by law. The exact scope of any exceptions requires legal review."] } },
    { vi: { title: "7. Bảo vệ dữ liệu cá nhân tại Việt Nam", body: ["Chính sách và hoạt động xử lý dữ liệu của TánGPT được xây dựng nhằm tuân thủ Nghị định 13/2023/NĐ-CP của Việt Nam về bảo vệ dữ liệu cá nhân. Nội dung và quy trình tuân thủ cần được luật sư Việt Nam xem xét trước khi phát hành chính thức."] }, en: { title: "7. Personal data protection in Vietnam", body: ["TánGPT's policy and data-processing practices are intended to comply with Vietnam's Decree 13/2023/NĐ-CP on personal data protection. The wording and compliance procedures require review by qualified Vietnamese legal counsel before final publication."] } },
    { vi: { title: "8. Liên hệ", body: ["Nếu có câu hỏi, yêu cầu hoặc khiếu nại về quyền riêng tư, vui lòng liên hệ: [PLACEHOLDER EMAIL - I will fill this in]."] }, en: { title: "8. Contact", body: ["For privacy questions, requests, or complaints, contact: [PLACEHOLDER EMAIL - I will fill this in]."] } },
  ]} />,
});
