import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Clock3, Copy, History, Lightbulb, LoaderCircle, LogOut, MessageCircle, Plus, RefreshCw, Send, Settings2, Sparkle, Trash2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ChatBubble } from "./ChatBubble";
import { Paywall } from "./Paywall";
import { PersonaCard } from "./PersonaCard";
import { RegionPicker } from "./RegionPicker";
import { useRegionTheme } from "./RegionTheme";
import { personas, regions, type AgeGroup, type Persona, type RegionKey } from "@/lib/tangpt-data";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

type Tab = "suggest" | "companion" | "history" | "profile";
type Generation = { id: string; input: string; createdAt: string; options: { style: string; text: string; why: string }[]; tip: string };
const sample = {
  options: [
    { style: "Vui vẻ", text: "Mệt dữ vậy hả. Cho mình ship qua một phần năng lượng tích cực được không nè?", why: "Nhẹ nhàng, có chút trêu và mở được đường cho em ấy kể thêm." },
    { style: "Chân thành", text: "Nghe thương quá. Em nghỉ ngơi chút đi nha, hôm nay có chuyện gì làm em mệt vậy?", why: "Thể hiện quan tâm thật lòng mà không vồ vập." },
    { style: "Tự tin", text: "Tối nay cứ nghỉ cho khỏe. Cuối tuần để mình bù cho em một buổi thật vui nhé.", why: "Chủ động vừa đủ, có lời mời rõ ràng nhưng vẫn tôn trọng." },
  ], tip: "Hỏi một câu thôi rồi chờ em ấy trả lời. Quan tâm không có nghĩa là phỏng vấn nha.",
};

export function AppExperience() {
  const [onboarded, setOnboarded] = useState(true); const [step, setStep] = useState(0); const [ageConfirmed, setAgeConfirmed] = useState(false); const [age, setAge] = useState<AgeGroup>("18-26");
  useEffect(() => setOnboarded(window.localStorage.getItem("tangpt-onboarded") === "1"), []);
  if (!onboarded) return <Onboarding step={step} setStep={setStep} ageConfirmed={ageConfirmed} setAgeConfirmed={setAgeConfirmed} age={age} setAge={setAge} finish={() => { window.localStorage.setItem("tangpt-onboarded", "1"); window.localStorage.setItem("tangpt-age", age); setOnboarded(true); }} />;
  return <AppShell />;
}

function Onboarding({ step, setStep, ageConfirmed, setAgeConfirmed, age, setAge, finish }: { step: number; setStep:(n:number)=>void; ageConfirmed:boolean; setAgeConfirmed:(v:boolean)=>void; age:AgeGroup; setAge:(v:AgeGroup)=>void; finish:()=>void }) {
  const { region, city } = useRegionTheme();
  async function done() { const { data } = await supabase.auth.getUser(); if (data.user) await supabase.from("profiles").upsert({ id: data.user.id, age_confirmed: true, default_region: region, default_city: city, age_group: age }); finish(); }
  return <main className="onboarding-shell"><header><span className="brand"><span>Tán</span>GPT<i /></span><div className="progress-dots">{[0,1,2].map(i => <i key={i} className={i <= step ? "active" : ""} />)}</div></header><section className="onboarding-card fade-up">
    {step === 0 && <><div className="line-illustration"><UserRound /></div><span className="step-label">BƯỚC 1/3</span><h1>Trước khi bắt đầu</h1><p>Ứng dụng dành cho người từ 18 tuổi trở lên.</p><label className="confirm-row"><input type="checkbox" checked={ageConfirmed} onChange={(e) => setAgeConfirmed(e.target.checked)} /><span><b>Tôi xác nhận tôi đủ 18 tuổi</b><small>Mình cần bạn xác nhận để giữ trải nghiệm phù hợp.</small></span></label><Button variant="gradient" size="lg" disabled={!ageConfirmed} onClick={() => setStep(1)}>Tiếp tục</Button></>}
    {step === 1 && <><span className="step-label">BƯỚC 2/3</span><h1>Em ấy đến từ đâu?</h1><p>Chọn đúng vùng, câu chữ sẽ nghe tự nhiên hơn hẳn.</p><RegionPicker /><Button variant="gradient" size="lg" onClick={() => setStep(2)}>Đã chọn {city}</Button></>}
    {step === 2 && <><div className="line-illustration"><Sparkle /></div><span className="step-label">BƯỚC 3/3</span><h1>Em ấy khoảng bao nhiêu tuổi?</h1><p>Mỗi lứa tuổi có một nhịp trò chuyện khác nhau.</p><div className="age-grid">{(["18-26","27-35","36+"] as AgeGroup[]).map(value => <button type="button" key={value} className={age===value?"active":""} onClick={() => setAge(value)}>{value}</button>)}</div><Button variant="gradient" size="lg" onClick={done}>Vào TánGPT</Button></>}
  </section></main>;
}

function AppShell() {
  const [tab,setTab]=useState<Tab>("suggest"); const [picker,setPicker]=useState(false); const {region,city}=useRegionTheme();
  return <main className="app-shell"><header className="app-top"><div><span className="brand"><span>Tán</span>GPT<i /></span><small>{tab === "suggest" ? "Nói hay, nhưng vẫn là bạn." : tab === "companion" ? "Một cuộc trò chuyện không phán xét." : tab === "history" ? "Những câu từng giúp bạn." : "Góc riêng của bạn."}</small></div><button type="button" onClick={()=>setPicker(!picker)} className="region-pill"><i />{regions[region].short} · {city}<Settings2 /></button></header>{picker && <div className="picker-popover fade-up"><RegionPicker /></div>}
    <div className="app-content">{tab==="suggest"&&<SuggestionTab/>}{tab==="companion"&&<CompanionTab/>}{tab==="history"&&<HistoryTab/>}{tab==="profile"&&<ProfileTab/>}</div>
    <nav className="bottom-nav">{[["suggest",Lightbulb,"Gợi ý"],["companion",MessageCircle,"Bạn gái AI"],["history",History,"Lịch sử"],["profile",UserRound,"Tôi"]].map(([key,Icon,label])=>{const I=Icon as typeof Lightbulb;return <button type="button" key={key as string} className={tab===key?"active":""} onClick={()=>setTab(key as Tab)}><I/><span>{label as string}</span></button>})}</nav>
  </main>;
}

function SuggestionTab() {
  const {region,city,setCity}=useRegionTheme(); const [mode,setMode]=useState<"reply"|"opener">("reply"); const [age,setAge]=useState<AgeGroup>("18-26"); const [text,setText]=useState(""); const [loading,setLoading]=useState(false); const [result,setResult]=useState<typeof sample|null>(null); const [copied,setCopied]=useState(""); const [paywall,setPaywall]=useState(false);
  async function generate(){if(!text.trim())return; if(text.trim().toLowerCase()==="limit_reached"){setPaywall(true);return;}setLoading(true);setResult(null);await new Promise(r=>setTimeout(r,1500));setResult(sample);setLoading(false);const entry:Generation={id:crypto.randomUUID(),input:text,createdAt:new Date().toISOString(),...sample};const all=JSON.parse(window.localStorage.getItem("tangpt-history")||"[]") as Generation[];window.localStorage.setItem("tangpt-history",JSON.stringify([entry,...all].slice(0,20)));}
  async function copy(value:string,style:string){await navigator.clipboard.writeText(value);setCopied(style);window.setTimeout(()=>setCopied(""),2000)}
  return <section className="tab-page"><div className="page-title"><span>LỜI HAY ĐÚNG LÚC</span><h1>Gợi ý cho bạn</h1></div><div className="segmented"><button type="button" className={mode==="reply"?"active":""} onClick={()=>setMode("reply")}>Trả lời tin nhắn</button><button type="button" className={mode==="opener"?"active":""} onClick={()=>setMode("opener")}>Mở lời</button></div><div className="filter-block"><label>Thành phố</label><div className="chip-scroll">{regions[region].cities.map(value=><button type="button" className={city===value?"chip chip-active":"chip"} onClick={()=>setCity(value)} key={value}>{value}</button>)}</div><label>Độ tuổi</label><div className="flex gap-2">{(["18-26","27-35","36+"] as AgeGroup[]).map(value=><button type="button" className={age===value?"chip chip-active":"chip"} onClick={()=>setAge(value)} key={value}>{value}</button>)}</div></div><div className="composer-card"><textarea value={text} maxLength={800} onChange={e=>setText(e.target.value)} placeholder={mode==="reply"?"Dán tin nhắn của em ấy vào đây...":"Mô tả profile, bio hoặc ảnh của em ấy..."}/><span>{text.length}/800</span></div><Button variant="gradient" size="lg" onClick={generate} disabled={loading||!text.trim()}>{loading?<><LoaderCircle className="animate-spin"/>Đang nghĩ câu duyên...</>:<><Send/>Gợi ý cho tôi</>}</Button>{result&&<div className="results fade-up"><div className="result-heading"><div><span>3 CÁCH TRẢ LỜI</span><h2>Chọn câu hợp bạn nhất</h2></div><Button variant="ghost" size="sm" onClick={generate}><RefreshCw/>Tạo lại</Button></div>{result.options.map(option=><article key={option.style}><h3>{option.style}</h3><ChatBubble text={option.text} why={option.why} copied={copied===option.style} onCopy={()=>copy(option.text,option.style)}/></article>)}<aside className="tip-box"><Lightbulb/><div><b>Mẹo nhỏ</b><p>{result.tip}</p></div></aside></div>}<Paywall open={paywall} onOpenChange={setPaywall}/></section>
}

function CompanionTab(){const {region}=useRegionTheme();const [selected,setSelected]=useState<Persona|null>(null);const [companions,setCompanions]=useState<Persona[]>([]);const [personality,setPersonality]=useState("Dịu dàng");const [mode,setMode]=useState("Trò chuyện");const navigate=useNavigate();const filtered=useMemo(()=>personas.filter(p=>p.region===region),[region]);function start(){if(!selected)return;setCompanions(v=>[...v,selected]);setSelected(null);}
  if(companions.length)return <section className="tab-page"><div className="page-title row-title"><div><span>CUỘC TRÒ CHUYỆN</span><h1>Bạn gái AI</h1></div><Button size="icon" variant="gradient" onClick={()=>setCompanions([])} aria-label="Thêm nhân vật"><Plus/></Button></div><div className="chat-list">{companions.map(p=><button type="button" key={p.id} onClick={()=>navigate({to:"/app/chat/$companionId",params:{companionId:p.id}})}><div className="avatar-orbit small"><span>{p.name[0]}</span></div><div><strong>{p.name}</strong><p>Chào bạn, hôm nay thế nào rồi?</p></div><time>21:08</time></button>)}</div></section>;
  return <section className="tab-page"><div className="page-title"><span>TRÒ CHUYỆN TỰ NHIÊN</span><h1>Chọn người bạn trò chuyện</h1><p>Cứ là chính mình. Đây là không gian để bạn trò chuyện và luyện tập.</p></div><div className="persona-carousel">{filtered.map(p=><PersonaCard key={p.id} persona={p} selected={selected?.id===p.id} onSelect={()=>setSelected(p)}/>)}</div>{selected&&<div className="confirm-sheet fade-up"><div className="sheet-handle"/><div className="flex items-center gap-3"><div className="avatar-orbit small"><span>{selected.name[0]}</span></div><div><h2>{selected.name}, {selected.age}</h2><p>{selected.job} · {selected.city}</p></div></div><label>Tính cách</label><div className="flex flex-wrap gap-2">{["Dịu dàng","Tinh nghịch","Chín chắn"].map(x=><button type="button" key={x} className={personality===x?"chip chip-active":"chip"} onClick={()=>setPersonality(x)}>{x}</button>)}</div><label>Chế độ</label><div className="segmented"><button type="button" className={mode==="Trò chuyện"?"active":""} onClick={()=>setMode("Trò chuyện")}>Trò chuyện</button><button type="button" className={mode!=="Trò chuyện"?"active":""} onClick={()=>setMode("Luyện tập tán tỉnh")}>Luyện tập tán tỉnh</button></div><Button variant="gradient" size="lg" onClick={start}>Bắt đầu nhắn tin</Button></div>}</section>;
}

function HistoryTab(){const [items,setItems]=useState<Generation[]>([]);useEffect(()=>setItems(JSON.parse(window.localStorage.getItem("tangpt-history")||"[]") as Generation[]),[]);return <section className="tab-page"><div className="page-title"><span>XEM LẠI KHI CẦN</span><h1>Lịch sử gợi ý</h1></div>{items.length===0?<div className="empty-state"><Clock3/><h2>Chưa có gì ở đây</h2><p>Tạo gợi ý đầu tiên, mình sẽ giữ lại giúp bạn.</p></div>:<div className="history-list">{items.map(item=><article key={item.id}><small>Vừa xong · {item.input}</small><p>{item.options[0].text}</p><Button variant="ghost" size="sm" onClick={()=>navigator.clipboard.writeText(item.options[0].text)}><Copy/>Sao chép</Button></article>)}</div>}</section>}
function ProfileTab(){const {region,city}=useRegionTheme();const navigate=useNavigate();async function logout(){await supabase.auth.signOut();window.localStorage.removeItem("tangpt-onboarded");navigate({to:"/login"})}return <section className="tab-page"><div className="page-title"><span>TÀI KHOẢN CỦA BẠN</span><h1>Tôi</h1></div><div className="profile-hero"><div className="avatar-orbit"><span>B</span></div><div><strong>Bạn của TánGPT</strong><p>Gói <b>Miễn phí</b></p></div></div><div className="settings-list"><div><span>Vùng mặc định</span><b>{regions[region].name} · {city}</b></div><div><span>Trạng thái</span><b className="text-primary">Miễn phí</b></div><button type="button" onClick={()=>{window.localStorage.removeItem("tangpt-history")}}><Trash2/>Xóa lịch sử trò chuyện</button><button type="button" onClick={logout}><LogOut/>Đăng xuất</button></div><div className="legal-links"><a href="#terms">Điều khoản</a><a href="#privacy">Quyền riêng tư</a></div></section>}
