import { useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Eye, EyeOff, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable/index";

export function LoginPage() {
  const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!email.includes("@")) return setError("Email này chưa đúng rồi bạn ơi."); if (password.length < 6) return setError("Mật khẩu cần ít nhất 6 ký tự nhé."); setBusy(true); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); setBusy(false); if (result.error) { setError(mode === "login" ? "Email hoặc mật khẩu chưa đúng. Thử lại nhé." : "Chưa tạo được tài khoản. Email này có thể đã được dùng."); return; } if (mode === "signup" && !result.data.session) { setError("Mình đã gửi email xác nhận. Bạn kiểm tra hộp thư nhé."); return; } navigate({ to: "/app" }); }
  async function google() { setError(""); const result = await lovable.auth.signInWithOAuth("google", { redirect_uri: window.location.origin + "/app" }); if (result.error) setError("Chưa kết nối được Google. Bạn thử lại nhé."); }
  return <main className="auth-shell"><Link to="/" className="brand"><span>Tán</span>GPT<i /></Link><section className="auth-card"><div className="auth-mark">T</div><h1>{mode === "login" ? "Chào bạn quay lại" : "Bắt đầu thôi bạn"}</h1><p>{mode === "login" ? "Vào lại cuộc trò chuyện đang hay dở." : "Tạo tài khoản, chọn đúng vùng rồi mình tính tiếp."}</p><div className="segmented"><button type="button" className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Đăng nhập</button><button type="button" className={mode === "signup" ? "active" : ""} onClick={() => setMode("signup")}>Đăng ký</button></div><form onSubmit={submit} className="space-y-4"><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" autoComplete="email" placeholder="ban@email.com" /></label><label>Mật khẩu<div className="password-field"><input value={password} onChange={(e) => setPassword(e.target.value)} type={show ? "text" : "password"} autoComplete={mode === "login" ? "current-password" : "new-password"} placeholder="Ít nhất 6 ký tự" /><button type="button" aria-label={show ? "Ẩn mật khẩu" : "Hiện mật khẩu"} onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <p className="form-message">{error}</p>}<Button variant="gradient" size="lg" className="w-full" disabled={busy}>{busy && <LoaderCircle className="animate-spin" />}{mode === "login" ? "Đăng nhập" : "Tạo tài khoản"}</Button></form><div className="divider"><span>hoặc</span></div><Button variant="outline" size="lg" className="w-full" onClick={google}><b className="google-g">G</b> Tiếp tục với Google</Button><small>Bằng việc tiếp tục, bạn đồng ý giao tiếp tử tế và tôn trọng.</small></section></main>;
}
