/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as ApiPublicCompanionDailyDecayRouteImport } from './routes/api/public/companion-daily-decay'
import { Route as AppChatCompanionIdRouteImport } from './routes/app.chat.$companionId'
import { Route as AppPersonaPersonaIdRouteImport } from './routes/app.persona.$personaId'
import { Route as AppAdminPersonasIndexRouteImport } from './routes/app.admin.personas.index'
import { Route as AppAdminPersonasPersonaIdRouteImport } from './routes/app.admin.personas.$personaId'
import { Route as ApiPublicAuthZaloCallbackRouteImport } from './routes/api/public/auth/zalo/callback'
import { Route as ApiPublicAuthZaloStartRouteImport } from './routes/api/public/auth/zalo/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCompanionDailyDecayRoute =
  ApiPublicCompanionDailyDecayRouteImport.update({
    id: '/api/public/companion-daily-decay',
    path: '/api/public/companion-daily-decay',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppChatCompanionIdRoute = AppChatCompanionIdRouteImport.update({
  id: '/chat/$companionId',
  path: '/chat/$companionId',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonaPersonaIdRoute = AppPersonaPersonaIdRouteImport.update({
  id: '/persona/$personaId',
  path: '/persona/$personaId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPersonasIndexRoute = AppAdminPersonasIndexRouteImport.update({
  id: '/admin/personas/',
  path: '/admin/personas/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPersonasPersonaIdRoute =
  AppAdminPersonasPersonaIdRouteImport.update({
    id: '/admin/personas/$personaId',
    path: '/admin/personas/$personaId',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicAuthZaloCallbackRoute =
  ApiPublicAuthZaloCallbackRouteImport.update({
    id: '/api/public/auth/zalo/callback',
    path: '/api/public/auth/zalo/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthZaloStartRoute = ApiPublicAuthZaloStartRouteImport.update({
  id: '/api/public/auth/zalo/start',
  path: '/api/public/auth/zalo/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/history': typeof AppHistoryRoute
  '/app/me': typeof AppMeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/companion-daily-decay': typeof ApiPublicCompanionDailyDecayRoute
  '/app/chat/$companionId': typeof AppChatCompanionIdRoute
  '/app/persona/$personaId': typeof AppPersonaPersonaIdRoute
  '/app/admin/personas/$personaId': typeof AppAdminPersonasPersonaIdRoute
  '/app/admin/personas/': typeof AppAdminPersonasIndexRoute
  '/api/public/auth/zalo/callback': typeof ApiPublicAuthZaloCallbackRoute
  '/api/public/auth/zalo/start': typeof ApiPublicAuthZaloStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/history': typeof AppHistoryRoute
  '/app/me': typeof AppMeRoute
  '/app': typeof AppIndexRoute
  '/api/public/companion-daily-decay': typeof ApiPublicCompanionDailyDecayRoute
  '/app/chat/$companionId': typeof AppChatCompanionIdRoute
  '/app/persona/$personaId': typeof AppPersonaPersonaIdRoute
  '/app/admin/personas/$personaId': typeof AppAdminPersonasPersonaIdRoute
  '/app/admin/personas': typeof AppAdminPersonasIndexRoute
  '/api/public/auth/zalo/callback': typeof ApiPublicAuthZaloCallbackRoute
  '/api/public/auth/zalo/start': typeof ApiPublicAuthZaloStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/history': typeof AppHistoryRoute
  '/app/me': typeof AppMeRoute
  '/app/': typeof AppIndexRoute
  '/api/public/companion-daily-decay': typeof ApiPublicCompanionDailyDecayRoute
  '/app/chat/$companionId': typeof AppChatCompanionIdRoute
  '/app/persona/$personaId': typeof AppPersonaPersonaIdRoute
  '/app/admin/personas/$personaId': typeof AppAdminPersonasPersonaIdRoute
  '/app/admin/personas/': typeof AppAdminPersonasIndexRoute
  '/api/public/auth/zalo/callback': typeof ApiPublicAuthZaloCallbackRoute
  '/api/public/auth/zalo/start': typeof ApiPublicAuthZaloStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/app/ai'
    | '/app/history'
    | '/app/me'
    | '/app/'
    | '/api/public/companion-daily-decay'
    | '/app/chat/$companionId'
    | '/app/persona/$personaId'
    | '/app/admin/personas/$personaId'
    | '/app/admin/personas/'
    | '/api/public/auth/zalo/callback'
    | '/api/public/auth/zalo/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/app/ai'
    | '/app/history'
    | '/app/me'
    | '/app'
    | '/api/public/companion-daily-decay'
    | '/app/chat/$companionId'
    | '/app/persona/$personaId'
    | '/app/admin/personas/$personaId'
    | '/app/admin/personas'
    | '/api/public/auth/zalo/callback'
    | '/api/public/auth/zalo/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/app/ai'
    | '/app/history'
    | '/app/me'
    | '/app/'
    | '/api/public/companion-daily-decay'
    | '/app/chat/$companionId'
    | '/app/persona/$personaId'
    | '/app/admin/personas/$personaId'
    | '/app/admin/personas/'
    | '/api/public/auth/zalo/callback'
    | '/api/public/auth/zalo/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCompanionDailyDecayRoute: typeof ApiPublicCompanionDailyDecayRoute
  ApiPublicAuthZaloCallbackRoute: typeof ApiPublicAuthZaloCallbackRoute
  ApiPublicAuthZaloStartRoute: typeof ApiPublicAuthZaloStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/companion-daily-decay': {
      id: '/api/public/companion-daily-decay'
      path: '/api/public/companion-daily-decay'
      fullPath: '/api/public/companion-daily-decay'
      preLoaderRoute: typeof ApiPublicCompanionDailyDecayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$companionId': {
      id: '/app/chat/$companionId'
      path: '/chat/$companionId'
      fullPath: '/app/chat/$companionId'
      preLoaderRoute: typeof AppChatCompanionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/persona/$personaId': {
      id: '/app/persona/$personaId'
      path: '/persona/$personaId'
      fullPath: '/app/persona/$personaId'
      preLoaderRoute: typeof AppPersonaPersonaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/personas/': {
      id: '/app/admin/personas/'
      path: '/admin/personas'
      fullPath: '/app/admin/personas/'
      preLoaderRoute: typeof AppAdminPersonasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/personas/$personaId': {
      id: '/app/admin/personas/$personaId'
      path: '/admin/personas/$personaId'
      fullPath: '/app/admin/personas/$personaId'
      preLoaderRoute: typeof AppAdminPersonasPersonaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/auth/zalo/callback': {
      id: '/api/public/auth/zalo/callback'
      path: '/api/public/auth/zalo/callback'
      fullPath: '/api/public/auth/zalo/callback'
      preLoaderRoute: typeof ApiPublicAuthZaloCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/zalo/start': {
      id: '/api/public/auth/zalo/start'
      path: '/api/public/auth/zalo/start'
      fullPath: '/api/public/auth/zalo/start'
      preLoaderRoute: typeof ApiPublicAuthZaloStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMeRoute: typeof AppMeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatCompanionIdRoute: typeof AppChatCompanionIdRoute
  AppPersonaPersonaIdRoute: typeof AppPersonaPersonaIdRoute
  AppAdminPersonasPersonaIdRoute: typeof AppAdminPersonasPersonaIdRoute
  AppAdminPersonasIndexRoute: typeof AppAdminPersonasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMeRoute: AppMeRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatCompanionIdRoute: AppChatCompanionIdRoute,
  AppPersonaPersonaIdRoute: AppPersonaPersonaIdRoute,
  AppAdminPersonasPersonaIdRoute: AppAdminPersonasPersonaIdRoute,
  AppAdminPersonasIndexRoute: AppAdminPersonasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicCompanionDailyDecayRoute: ApiPublicCompanionDailyDecayRoute,
  ApiPublicAuthZaloCallbackRoute: ApiPublicAuthZaloCallbackRoute,
  ApiPublicAuthZaloStartRoute: ApiPublicAuthZaloStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
